# Aws Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# Ref : https://github.com/backspace-academy/aws-nodejs-sample-codebuild/blob/master/buildspec.yml
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

env:
  exported-variables:
    - env
    - cfdistid  #CloudFront Distribution ID to clear the cache

phases:
  install:
    runtime-versions:
      nodejs: 12 
    commands:
      - echo Build is starting now...
      - echo Installing source NPM dependencies...
      - npm i

  pre_build:
    commands:
      - echo Running unit tests...
      - npm run test

  build:
    commands:
      - echo Dev Build starting...
      - npm run build:$env
      - echo Checking build artifacts
      - cd dist && ls -la
      - cd ..
  post_build:
    commands:
      - echo Checking Environment Variables
      - echo environment - $env
      - echo cfdistid - $cfdistid

artifacts:
  files:
    - '**/*'